### ISSUE TITLE
Clock scramble says "Invalid Scramble"

### ISSUE THREAD

**Issue by big213** [cubing/scramble-display#3]
It seems like there is some inconsistency in the notation for clock. Our notation: `UR4- DR1+ DL5+ UL1- U1+ R0+ D2- L1+ ALL4+ y2 U1- R4- D0+ L3+ ALL1+ UR DR DL`

scramble-display gives an error: `Invalid scramble`

Not sure which notation is more widely used, do you have any suggestions?

**Comment by lgarron** [comment]
That scramble works, as far as I can tell!

https://jsfiddle.net/lgarron/2sb1xp40/

Is it possible that you're adding extra padding or newlines accidentally? Try making sure there's a space between any two adjacent moves, and nowhere else.

**Comment by big213** [comment]
Just upgraded from 0.0.5 to 0.1.0 and now we're good, silly mistake on my part. Thanks for looking into it!
