### ISSUE TITLE
3D visualization background is always checkered

### ISSUE THREAD

**Issue by big213** [cubing/scramble-display#7]
Seems to have started happening between 0.1.1 and 0.2.1

`<scramble-display scramble="F' D F2 L2 U' R2 U' F2 D2 R2 F2 U2 F R' B F D' B2 U B'" visualisation="3D"></scramble-display>`

**Comment by lgarron** [comment]
Indeed, this is from 1a1f6fdc043d4cb8295f75f5d4693be7da4c8213. I need to push the checkered CSS configuration into `cubing.js` itself.

**Comment by lgarron** [comment]
This should be fixed in `v0.2.3`! Thanks for reporting, it was valuable to know that this was happening!
